# Generated by Django 4.1.1 on 2022-09-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_incharge_id', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('opinion', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_resolved', models.DateTimeField(auto_now_add=True)),
                ('solution', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Started', 'Started'), ('Resolved', 'Resolved')], max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
