# Generated by Django 4.1.1 on 2022-09-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_phone_ticket_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='name',
        ),
    ]
