# Generated by Django 4.1.1 on 2022-09-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_department_ticket_remove_customer_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='phone',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='depart_incharge_id',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.department'),
        ),
    ]
